// 전문가 20명 + 각 2개 프로그램 스펙 (총 40개).
// 이메일: 테스트 로그인 계정 2개(@test.com)만 비밀번호를 가지며,
// 나머지는 로그인 불가(@seed.invalid, passwordHash null) — 실제 개인정보 아님.
export type Tier = 'low' | 'mid' | 'high';

export interface ProgramSpec {
  slugSuffix: string;
  categorySlug: string;
  title: string;
  short: string;
  full: string;
  programType: 'PRIVATE' | 'GROUP';
  bookingType: 'INSTANT' | 'REQUEST';
  isOnline?: boolean;
  durationDays: number;
  sessionCount: number;
  maxParticipants: number;
  tier: Tier;
  petFriendly?: boolean;
  childFriendly?: boolean;
  accommodationIncluded?: boolean;
  transportIncluded?: boolean;
  featured?: boolean;
  includes: string[];
  excludes?: string[];
  requirements?: string[];
  meetingPoint?: string;
}

export interface ExpertSeed {
  slug: string;
  email: string;
  hasPassword?: boolean; // true면 seed 시 Test1234! 해시 부여 (테스트 계정 전용)
  name: string;
  fullName: string;
  displayName: string;
  bio: string;
  specialties: string[];
  languages: string[];
  yearsOfExperience: number;
  baseCitySlug: string;
  serviceAreaSlugs: string[];
  verificationStatus: 'APPROVED' | 'PENDING';
  programs: ProgramSpec[];
}

export const expertSeeds: ExpertSeed[] = [
  {
    slug: 'kim-minjun',
    email: 'expert@test.com', // 승인된 전문가 테스트 계정
    hasPassword: true,
    name: '김민준',
    fullName: '김민준',
    displayName: '김민준 트레이너',
    bio: '제주에서 10년째 활동 중인 퍼스널 트레이너. 한 달이면 몸의 방향이 바뀝니다. 체형 분석부터 식단까지 함께 설계합니다.',
    specialties: ['fitness', 'diet-wellness'],
    languages: ['ko', 'en'],
    yearsOfExperience: 10,
    baseCitySlug: 'jeju',
    serviceAreaSlugs: ['jeju'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'monthly-pt',
        categorySlug: 'fitness',
        title: '제주 한달 집중 퍼스널 트레이닝',
        short: '주 3회, 12회 완성 1:1 체형 교정과 근력 프로그램.',
        full: '첫 주 체형·체력 분석 후 매주 목표를 조정하는 12회 1:1 트레이닝입니다. 제주 시내 프라이빗 짐에서 진행하며, 식단 가이드와 주간 리포트를 제공합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 12,
        maxParticipants: 1,
        tier: 'high',
        featured: true,
        includes: [
          '체형·체력 분석 1회',
          '1:1 트레이닝 12회',
          '주간 식단 가이드',
          '운동 기록 리포트',
        ],
        excludes: ['짐 외 개인 운동복·용품'],
        requirements: ['가벼운 운동복', '실내 운동화'],
        meetingPoint: '제주시 연동 프라이빗 짐',
      },
      {
        slugSuffix: 'sunrise-bootcamp',
        categorySlug: 'diet-wellness',
        title: '아침을 여는 해변 부트캠프 4주',
        short: '삼양 해변에서 주 4회, 소그룹 아침 운동 습관 만들기.',
        full: '해 뜨는 해변에서 하루를 시작하는 소그룹 부트캠프입니다. 유산소와 맨몸 근력을 섞어 4주간 운동 습관을 만드는 데 집중합니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 16,
        maxParticipants: 8,
        tier: 'mid',
        includes: ['그룹 트레이닝 16회', '요가 매트 대여', '주간 체중·컨디션 체크'],
        meetingPoint: '삼양검은모래해변 입구',
      },
    ],
  },
  {
    slug: 'shin-haneul',
    email: 'expert-pending@test.com', // 승인 대기 전문가 테스트 계정
    hasPassword: true,
    name: '신하늘',
    fullName: '신하늘',
    displayName: '신하늘 웰니스 코치',
    bio: '요가와 식단 코칭을 결합한 웰니스 리셋 프로그램을 준비하고 있습니다. 현재 플랫폼 인증 심사 중입니다.',
    specialties: ['diet-wellness'],
    languages: ['ko'],
    yearsOfExperience: 4,
    baseCitySlug: 'jeju',
    serviceAreaSlugs: ['jeju'],
    verificationStatus: 'PENDING',
    programs: [
      {
        slugSuffix: 'wellness-reset',
        categorySlug: 'diet-wellness',
        title: '제주 웰니스 리셋 4주 (준비 중)',
        short: '식단·움직임·수면을 함께 정리하는 4주 코칭.',
        full: '몸의 리듬을 되찾는 4주 웰니스 코칭 프로그램입니다. 인증 심사 완료 후 공개됩니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 1,
        tier: 'mid',
        includes: ['주 2회 코칭 세션', '식단 일지 피드백'],
      },
      {
        slugSuffix: 'detox-walk',
        categorySlug: 'diet-wellness',
        title: '오름 디톡스 워킹 (준비 중)',
        short: '오름을 걸으며 몸을 비우는 소그룹 프로그램.',
        full: '매주 다른 오름을 걸으며 가벼운 식단 미션을 병행하는 소그룹 디톡스 프로그램입니다. 인증 심사 완료 후 공개됩니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 6,
        tier: 'low',
        includes: ['오름 가이드 워킹 8회', '식단 미션 가이드'],
      },
    ],
  },
  {
    slug: 'lee-seoyeon',
    email: 'lee.seoyeon@seed.invalid',
    name: '이서연',
    fullName: '이서연',
    displayName: '이서연 요가',
    bio: '인도 리시케시에서 수련한 하타·빈야사 지도자. 제주 자연 속에서 호흡과 움직임의 균형을 안내합니다.',
    specialties: ['yoga-pilates', 'meditation-healing'],
    languages: ['ko', 'en'],
    yearsOfExperience: 8,
    baseCitySlug: 'jeju',
    serviceAreaSlugs: ['jeju'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'morning-yoga',
        categorySlug: 'yoga-pilates',
        title: '제주 아침 요가 한 달',
        short: '평일 아침, 바다가 보이는 스튜디오에서 시작하는 하루.',
        full: '월요일부터 금요일까지 이어지는 아침 요가 클래스입니다. 호흡·태양경배·이완의 순서로 하루의 리듬을 만들고, 주 1회 명상 세션이 포함됩니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 20,
        maxParticipants: 10,
        tier: 'mid',
        featured: true,
        includes: ['아침 클래스 20회', '주 1회 명상 세션', '매트·소도구 대여'],
        meetingPoint: '애월 해안도로 요가 스튜디오',
      },
      {
        slugSuffix: 'private-pilates',
        categorySlug: 'yoga-pilates',
        title: '1:1 필라테스 체형 교정 4주',
        short: '기구 필라테스로 자세와 코어를 다시 세우는 12회.',
        full: '개인의 체형과 통증 이력을 바탕으로 기구 필라테스 커리큘럼을 설계합니다. 12회 동안 자세 정렬과 코어 안정화에 집중합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 12,
        maxParticipants: 1,
        tier: 'high',
        includes: ['체형 분석', '기구 필라테스 12회', '홈 트레이닝 가이드'],
      },
    ],
  },
  {
    slug: 'park-dohyun',
    email: 'park.dohyun@seed.invalid',
    name: '박도현',
    fullName: '박도현',
    displayName: '박도현 서프',
    bio: '중문 바다에서 15년. 초보가 파도 위에 서는 순간을 가장 좋아하는 서핑 코치입니다.',
    specialties: ['surfing'],
    languages: ['ko', 'en'],
    yearsOfExperience: 15,
    baseCitySlug: 'jeju',
    serviceAreaSlugs: ['jeju'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'surf-basic',
        categorySlug: 'surfing',
        title: '중문 서핑 입문 한 달',
        short: '패들부터 테이크오프까지, 주 2회 소그룹 레슨.',
        full: '중문색달해변에서 진행하는 입문 과정입니다. 8회 레슨으로 패들링, 테이크오프, 파도 읽기를 익히고 자유 서핑 시간을 함께합니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 30,
        sessionCount: 8,
        maxParticipants: 6,
        tier: 'mid',
        includes: ['레슨 8회', '보드·슈트 대여', '안전 교육'],
        requirements: ['기초 수영 가능'],
        meetingPoint: '중문색달해변 서핑스쿨',
      },
      {
        slugSuffix: 'surf-private',
        categorySlug: 'surfing',
        title: '서핑 1:1 집중 코칭',
        short: '영상 분석과 함께 실력을 끌어올리는 개인 코칭 10회.',
        full: '초중급 서퍼를 위한 1:1 코칭입니다. 라인업 포지셔닝과 파도 선택을 영상 분석과 함께 교정합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 10,
        maxParticipants: 1,
        tier: 'high',
        includes: ['1:1 코칭 10회', '세션 영상 분석', '보드 대여'],
        requirements: ['테이크오프 가능 수준'],
      },
    ],
  },
  {
    slug: 'choi-haeun',
    email: 'choi.haeun@seed.invalid',
    name: '최하은',
    fullName: '최하은',
    displayName: '하은의 제주살이',
    bio: '제주 토박이 문화 해설사. 관광지가 아닌 골목과 시장, 사람의 이야기로 제주를 소개합니다. 반려견 두 마리와 삽니다.',
    specialties: ['travel-culture', 'pet-companion'],
    languages: ['ko'],
    yearsOfExperience: 7,
    baseCitySlug: 'jeju',
    serviceAreaSlugs: ['jeju'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'local-life',
        categorySlug: 'travel-culture',
        title: '진짜 제주 로컬 라이프 4주',
        short: '오일장·해녀·마을 골목 — 주 1회 로컬 동행 투어.',
        full: '매주 하나의 주제로 제주의 생활 문화를 만나는 동행 프로그램입니다. 오일장 장보기, 해녀 이야기, 원도심 골목 산책이 포함됩니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 8,
        tier: 'low',
        featured: true,
        childFriendly: true,
        includes: ['주 1회 동행 투어 4회', '로컬 맛집·생활 지도'],
        meetingPoint: '제주 동문시장 정문',
      },
      {
        slugSuffix: 'pet-settle',
        categorySlug: 'pet-companion',
        title: '반려동물과 제주 정착 가이드',
        short: '동물병원·펫 프렌들리 공간까지, 반려 동반 한달살기 셋업.',
        full: '반려동물 동반 입도 준비부터 동물병원, 펫 프렌들리 카페·해변·숙소 정보까지 1:1로 정착을 돕습니다. 주 1회 산책 모임도 함께합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 4,
        maxParticipants: 2,
        tier: 'mid',
        petFriendly: true,
        includes: ['정착 컨설팅 2회', '반려 동반 스팟 지도', '주 1회 산책 모임'],
      },
    ],
  },
  {
    slug: 'jung-woojin',
    email: 'jung.woojin@seed.invalid',
    name: '정우진',
    fullName: '정우진',
    displayName: '정우진 · 방콕 워케이션',
    bio: '방콕에서 코워킹 스페이스를 운영하는 6년 차 노마드. 비자, 숙소, 작업 환경까지 워케이션의 처음을 함께 설계합니다.',
    specialties: ['remote-work', 'startup-networking'],
    languages: ['ko', 'en', 'th'],
    yearsOfExperience: 6,
    baseCitySlug: 'bangkok',
    serviceAreaSlugs: ['bangkok', 'chiang-mai'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'workation-setup',
        categorySlug: 'remote-work',
        title: '방콕 워케이션 셋업 컨시어지',
        short: '숙소·코워킹·통신·비자 — 도착 첫 주에 모든 셋업 완료.',
        full: '도착 전 화상 상담으로 요구사항을 정리하고, 첫 주 안에 숙소 주변 코워킹, 유심, 교통, 은행 업무까지 정착을 마칩니다. 한 달간 메신저 컨시어지가 포함됩니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 3,
        maxParticipants: 2,
        tier: 'mid',
        featured: true,
        includes: ['사전 화상 상담', '정착 동행 2회', '30일 메신저 컨시어지', '코워킹 1주 패스'],
      },
      {
        slugSuffix: 'bkk-founders',
        categorySlug: 'startup-networking',
        title: '방콕 파운더스 네트워킹 4주',
        short: '현지 창업가·투자자와의 주 1회 밋업과 소개.',
        full: '동남아 진출을 고민하는 창업가를 위한 네트워킹 프로그램입니다. 주 1회 큐레이션 밋업과 관심 분야 현지 관계자 소개를 제공합니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 10,
        tier: 'mid',
        includes: ['큐레이션 밋업 4회', '1:1 소개 2건', '시장 개요 브리핑'],
      },
    ],
  },
  {
    slug: 'anong-siri',
    email: 'anong.siri@seed.invalid',
    name: 'Anong Siri',
    fullName: 'Anong Siri',
    displayName: '아농의 타이 키친',
    bio: '방콕 요리학교 출신 셰프. 수상시장 장보기부터 우리 집 주방까지, 태국 가정식의 진짜 맛을 알려드립니다.',
    specialties: ['cooking-food'],
    languages: ['th', 'en'],
    yearsOfExperience: 12,
    baseCitySlug: 'bangkok',
    serviceAreaSlugs: ['bangkok'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'thai-kitchen',
        categorySlug: 'cooking-food',
        title: '방콕 시장과 부엌 4주',
        short: '시장 투어와 쿠킹 클래스로 배우는 태국 가정식 8회.',
        full: '주 2회, 시장에서 재료를 고르고 바로 요리하는 실전형 클래스입니다. 팟타이부터 똠얌꿍, 커리 페이스트 만들기까지 다룹니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 6,
        tier: 'mid',
        featured: true,
        includes: ['시장 투어 4회', '쿠킹 클래스 8회', '레시피 북', '재료비'],
        meetingPoint: '방콕 클롱토이 시장 입구',
      },
      {
        slugSuffix: 'chef-table',
        categorySlug: 'cooking-food',
        title: '1:1 셰프 테이블 심화 과정',
        short: '메뉴 개발까지 함께하는 개인 맞춤 심화 쿠킹.',
        full: '요리 경험자를 위한 1:1 심화 과정입니다. 원하는 지역 요리를 골라 소스·향신료의 원리부터 플레이팅까지 깊게 배웁니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 6,
        maxParticipants: 1,
        tier: 'high',
        includes: ['1:1 클래스 6회', '맞춤 레시피 개발', '재료비'],
      },
    ],
  },
  {
    slug: 'somchai-prasert',
    email: 'somchai.prasert@seed.invalid',
    name: 'Somchai Prasert',
    fullName: 'Somchai Prasert',
    displayName: '쏨차이 태국어 교실',
    bio: '쭐라롱껀대 언어교육 석사. 성조가 두렵지 않게, 생활 속 태국어를 가르칩니다.',
    specialties: ['language-study'],
    languages: ['th', 'en', 'ko'],
    yearsOfExperience: 9,
    baseCitySlug: 'bangkok',
    serviceAreaSlugs: ['bangkok'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'thai-immersion',
        categorySlug: 'language-study',
        title: '태국어 몰입 1:1 한 달',
        short: '주 3회 1:1 수업 + 시장·카페 현장 실습.',
        full: '기초 발음과 성조부터 시작해 4주 뒤 시장에서 흥정할 수 있는 수준을 목표로 합니다. 수업의 절반은 거리에서 진행합니다.',
        programType: 'PRIVATE',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 12,
        maxParticipants: 1,
        tier: 'mid',
        includes: ['1:1 수업 12회', '현장 실습 4회', '교재'],
      },
      {
        slugSuffix: 'thai-online-prep',
        categorySlug: 'language-study',
        title: '출발 전 온라인 태국어 준비반',
        short: '한달살기 출발 전 4주, 온라인 소그룹 기초 과정.',
        full: '태국행이 확정된 분들을 위한 온라인 준비 과정입니다. 인사·숫자·교통·주문 표현을 4주에 끝냅니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        isOnline: true,
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 8,
        tier: 'low',
        includes: ['온라인 수업 8회', '녹화본 제공', '학습 자료'],
      },
    ],
  },
  {
    slug: 'han-jiwoo',
    email: 'han.jiwoo@seed.invalid',
    name: '한지우',
    fullName: '한지우',
    displayName: '지우의 치앙마이',
    bio: '치앙마이 5년 차 정착 컨시어지. 노마드부터 은퇴 준비까지, 님만해민의 골목골목을 가장 잘 아는 사람.',
    specialties: ['remote-work', 'retirement-longstay'],
    languages: ['ko', 'en', 'th'],
    yearsOfExperience: 5,
    baseCitySlug: 'chiang-mai',
    serviceAreaSlugs: ['chiang-mai', 'bangkok'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'nomad-settle',
        categorySlug: 'remote-work',
        title: '치앙마이 노마드 정착 패키지',
        short: '숙소·카페·코워킹 지도와 동행 셋업, 노마드 커뮤니티 연결.',
        full: '치앙마이 도착 후 일주일 안에 일할 수 있는 환경을 만듭니다. 동네별 숙소 상담, 코워킹 투어, 현지 노마드 커뮤니티 소개가 포함됩니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 3,
        maxParticipants: 2,
        tier: 'mid',
        featured: true,
        includes: ['정착 동행 2회', '커뮤니티 밋업 초대', '30일 메신저 지원'],
      },
      {
        slugSuffix: 'retire-preview',
        categorySlug: 'retirement-longstay',
        title: '치앙마이 은퇴 한달 미리살기',
        short: '병원·주거·비자·생활비 — 은퇴 장기 체류 사전 답사 프로그램.',
        full: '은퇴 후 장기 체류를 고민하는 분들을 위해 주거 지역 답사, 국제병원 안내, 장기 비자와 생활비 시뮬레이션을 4주에 걸쳐 함께합니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 6,
        maxParticipants: 6,
        tier: 'mid',
        includes: ['지역 답사 3회', '병원·보험 안내', '생활비 워크숍'],
      },
    ],
  },
  {
    slug: 'nim-chaidee',
    email: 'nim.chaidee@seed.invalid',
    name: 'Nim Chaidee',
    fullName: 'Nim Chaidee',
    displayName: '님의 마음챙김',
    bio: '위빠사나 수행 10년. 치앙마이 사원과 숲에서 멈추는 법을 안내하는 명상 지도자입니다.',
    specialties: ['meditation-healing'],
    languages: ['th', 'en'],
    yearsOfExperience: 10,
    baseCitySlug: 'chiang-mai',
    serviceAreaSlugs: ['chiang-mai'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'mindful-month',
        categorySlug: 'meditation-healing',
        title: '치앙마이 마음챙김 한 달',
        short: '사원 명상과 숲 걷기 명상, 주 2회 소그룹 수련.',
        full: '도이수텝 자락의 조용한 공간에서 주 2회 진행하는 명상 수련입니다. 호흡 관찰부터 걷기 명상까지, 일상에 가져갈 수 있는 루틴을 만듭니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 8,
        tier: 'mid',
        includes: ['소그룹 수련 8회', '사원 명상 안내 1회', '수련 일지'],
      },
      {
        slugSuffix: 'private-meditation',
        categorySlug: 'meditation-healing',
        title: '1:1 명상 코칭 4주',
        short: '개인의 상태에 맞춘 주 1회 명상 코칭과 데일리 가이드.',
        full: '번아웃, 불면 등 개인의 상태를 듣고 맞춤 수련을 설계하는 1:1 과정입니다. 주 1회 세션과 매일 아침 오디오 가이드를 제공합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 1,
        tier: 'low',
        includes: ['1:1 세션 4회', '데일리 오디오 가이드'],
      },
    ],
  },
  {
    slug: 'oh-sungmin',
    email: 'oh.sungmin@seed.invalid',
    name: '오성민',
    fullName: '오성민',
    displayName: '성민 서프캠프',
    bio: '푸껫 카타비치의 한국인 서핑·프리다이빙 강사. 바다에서 보내는 한 달을 설계합니다.',
    specialties: ['surfing'],
    languages: ['ko', 'en'],
    yearsOfExperience: 8,
    baseCitySlug: 'phuket',
    serviceAreaSlugs: ['phuket', 'koh-samui'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'surf-camp',
        categorySlug: 'surfing',
        title: '푸껫 서핑 캠프 4주',
        short: '카타비치 주 3회 레슨과 무제한 보드 대여.',
        full: '몬순 시즌 파도가 좋은 카타비치에서 진행하는 4주 캠프입니다. 12회 레슨과 캠프 기간 보드 무제한 대여가 포함됩니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 12,
        maxParticipants: 6,
        tier: 'mid',
        includes: ['레슨 12회', '보드 무제한 대여', '수상 안전 교육'],
        requirements: ['기초 수영 가능'],
        meetingPoint: '카타비치 서프하우스',
      },
      {
        slugSuffix: 'freedive-basic',
        categorySlug: 'surfing',
        title: '프리다이빙 입문 과정',
        short: '이론부터 오픈워터까지, 자격증 취득 소그룹 과정.',
        full: '호흡 이론과 풀 세션을 거쳐 라차섬 오픈워터 세션까지 진행하는 프리다이빙 입문 과정입니다. 수료 시 국제 자격증이 발급됩니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 14,
        sessionCount: 6,
        maxParticipants: 4,
        tier: 'mid',
        transportIncluded: true,
        includes: ['이론·풀 세션 4회', '오픈워터 2회', '장비 대여', '자격증 발급비'],
        requirements: ['수영 200m 가능', '건강 자가진단서'],
      },
    ],
  },
  {
    slug: 'mali-kanya',
    email: 'mali.kanya@seed.invalid',
    name: 'Mali Kanya',
    fullName: 'Mali Kanya',
    displayName: '말리 웰니스',
    bio: '푸껫 리조트 스파 15년 경력의 웰니스 디렉터. 몸을 비우고 채우는 리트리트를 만듭니다.',
    specialties: ['diet-wellness', 'yoga-pilates'],
    languages: ['th', 'en'],
    yearsOfExperience: 15,
    baseCitySlug: 'phuket',
    serviceAreaSlugs: ['phuket'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'wellness-retreat',
        categorySlug: 'diet-wellness',
        title: '푸껫 웰니스 리트리트 4주',
        short: '숙소·식단·스파·요가가 포함된 올인클루시브 리트리트.',
        full: '나이한 비치 인근 리트리트 하우스에서 진행하는 4주 프로그램입니다. 디톡스 식단, 데일리 요가, 주 1회 스파 테라피가 포함됩니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 28,
        maxParticipants: 8,
        tier: 'high',
        featured: true,
        accommodationIncluded: true,
        includes: ['리트리트 하우스 숙박', '1일 2식 디톡스 식단', '데일리 요가', '주 1회 스파'],
        excludes: ['항공권', '개인 경비'],
      },
      {
        slugSuffix: 'detox-coaching',
        categorySlug: 'diet-wellness',
        title: '디톡스 식단 1:1 코칭',
        short: '현지 식재료로 구성하는 4주 개인 식단 관리.',
        full: '태국 현지에서 구할 수 있는 재료로 실천 가능한 디톡스 식단을 설계하고 주 2회 점검합니다.',
        programType: 'PRIVATE',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 1,
        tier: 'mid',
        includes: ['식단 설계', '주 2회 코칭', '장보기 동행 1회'],
      },
    ],
  },
  {
    slug: 'kwon-nara',
    email: 'kwon.nara@seed.invalid',
    name: '권나라',
    fullName: '권나라',
    displayName: '나라 요가 리트리트',
    bio: '코사무이에서 요가 리트리트 센터를 운영합니다. 파도 소리와 함께하는 수련의 힘을 믿습니다.',
    specialties: ['yoga-pilates', 'meditation-healing'],
    languages: ['ko', 'en'],
    yearsOfExperience: 11,
    baseCitySlug: 'koh-samui',
    serviceAreaSlugs: ['koh-samui', 'phuket'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'sunset-retreat',
        categorySlug: 'yoga-pilates',
        title: '코사무이 선셋 요가 리트리트',
        short: '숙박 포함 4주 — 일몰 요가와 사운드 힐링.',
        full: '라마이 언덕 리트리트 센터에서 머물며 매일 일몰 요가와 주 2회 사운드 힐링 세션을 경험하는 4주 과정입니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 28,
        maxParticipants: 10,
        tier: 'high',
        accommodationIncluded: true,
        includes: ['리트리트 숙박', '데일리 선셋 요가', '사운드 힐링 8회', '조식'],
        excludes: ['항공권'],
      },
      {
        slugSuffix: 'morning-flow',
        categorySlug: 'yoga-pilates',
        title: '아침 빈야사 플로우 클래스',
        short: '차웽 비치 앞 스튜디오, 평일 아침 드롭인 한 달 패스.',
        full: '차웽 비치 스튜디오에서 진행하는 아침 빈야사 클래스 한 달 무제한 패스입니다. 초급부터 참여 가능합니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 30,
        sessionCount: 20,
        maxParticipants: 12,
        tier: 'low',
        includes: ['평일 아침 클래스 무제한', '매트 대여'],
        meetingPoint: '차웽 비치 요가 스튜디오',
      },
    ],
  },
  {
    slug: 'tran-minh',
    email: 'tran.minh@seed.invalid',
    name: 'Tran Minh',
    fullName: 'Tran Van Minh',
    displayName: '민 골프 아카데미',
    bio: 'KPGA 투어 캐디 출신, 다낭 골프 아카데미 헤드코치. 전지훈련의 성지에서 스코어를 바꿉니다.',
    specialties: ['golf'],
    languages: ['vi', 'ko', 'en'],
    yearsOfExperience: 13,
    baseCitySlug: 'da-nang',
    serviceAreaSlugs: ['da-nang'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'golf-camp',
        categorySlug: 'golf',
        title: '다낭 골프 전지훈련 한 달',
        short: '주 3회 레슨 + 주 2회 라운딩, 픽업 포함 집중 캠프.',
        full: '몽고메리·바나힐스 등 다낭 명문 코스에서 진행하는 전지훈련입니다. 스윙 교정 레슨 12회와 라운딩 8회, 숙소-코스 픽업이 포함됩니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 20,
        maxParticipants: 2,
        tier: 'high',
        featured: true,
        transportIncluded: true,
        includes: ['레슨 12회', '라운딩 8회(그린피 포함)', '코스 픽업', '스윙 영상 분석'],
        excludes: ['캐디피·카트비', '식사'],
      },
      {
        slugSuffix: 'group-lesson',
        categorySlug: 'golf',
        title: '소그룹 필드 레슨 4주',
        short: '연습장 레슨과 월 2회 필드 실습을 결합한 그룹 과정.',
        full: '주 2회 연습장 레슨으로 기본기를 다지고 월 2회 필드에서 실전 감각을 익히는 소그룹 과정입니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 10,
        maxParticipants: 4,
        tier: 'mid',
        includes: ['연습장 레슨 8회', '필드 실습 2회', '연습장 이용료'],
      },
    ],
  },
  {
    slug: 'yoon-jia',
    email: 'yoon.jia@seed.invalid',
    name: '윤지아',
    fullName: '윤지아',
    displayName: '지아네 가족 다낭',
    bio: '두 아이와 다낭에 정착한 4년 차. 가족 단위 한달살기의 현실적인 모든 것을 안내합니다.',
    specialties: ['family-kids', 'travel-culture'],
    languages: ['ko', 'en'],
    yearsOfExperience: 4,
    baseCitySlug: 'da-nang',
    serviceAreaSlugs: ['da-nang', 'nha-trang'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'family-settle',
        categorySlug: 'family-kids',
        title: '가족 한달살기 정착 컨시어지',
        short: '아이 학교·병원·놀이 스팟까지, 가족 맞춤 정착 지원.',
        full: '아이 연령에 맞는 국제학교 단기 프로그램, 소아과, 키즈 카페와 해변 스팟까지 — 가족의 한 달을 안전하고 알차게 설계합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 30,
        sessionCount: 4,
        maxParticipants: 4,
        tier: 'mid',
        childFriendly: true,
        includes: ['가족 맞춤 정착 상담', '동행 지원 2회', '30일 메신저 지원'],
      },
      {
        slugSuffix: 'kids-explore',
        categorySlug: 'family-kids',
        title: '다낭 키즈 체험 클럽 4주',
        short: '주 2회 아이 동반 자연·문화 체험 소그룹.',
        full: '마블마운틴 탐험, 바구니배 타기, 베트남 전통 등 만들기 등 아이 눈높이의 체험을 주 2회 진행합니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 6,
        tier: 'low',
        childFriendly: true,
        includes: ['체험 활동 8회', '재료비·입장료', '활동 사진 앨범'],
      },
    ],
  },
  {
    slug: 'nguyen-lan',
    email: 'nguyen.lan@seed.invalid',
    name: 'Nguyen Lan',
    fullName: 'Nguyen Thi Lan',
    displayName: '란 선생님의 베트남어',
    bio: '호찌민 인문사회대 한국학과 강사. 한국어로 설명하는 가장 쉬운 베트남어 수업.',
    specialties: ['language-study'],
    languages: ['vi', 'ko'],
    yearsOfExperience: 7,
    baseCitySlug: 'ho-chi-minh',
    serviceAreaSlugs: ['ho-chi-minh'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'viet-immersion',
        categorySlug: 'language-study',
        title: '베트남어 몰입 한 달',
        short: '주 3회 1:1 + 카페·시장 현장 수업.',
        full: '성조와 발음부터 시작해 4주 후 로컬 식당에서 주문하고 흥정할 수 있는 실전 회화를 목표로 합니다.',
        programType: 'PRIVATE',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 12,
        maxParticipants: 1,
        tier: 'mid',
        includes: ['1:1 수업 12회', '현장 수업 4회', '교재'],
      },
      {
        slugSuffix: 'viet-online',
        categorySlug: 'language-study',
        title: '온라인 베트남어 기초반',
        short: '출발 전 4주 온라인 소그룹 — 생존 회화 완성.',
        full: '베트남 한달살기 출발 전 꼭 필요한 표현만 모아 4주간 온라인으로 진행하는 소그룹 기초반입니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        isOnline: true,
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 8,
        tier: 'low',
        includes: ['온라인 수업 8회', '녹화본', '표현 노트'],
      },
    ],
  },
  {
    slug: 'seo-junho',
    email: 'seo.junho@seed.invalid',
    name: '서준호',
    fullName: '서준호',
    displayName: '준호 · 사이공 비즈니스',
    bio: '호찌민에서 F&B 스타트업 2회 창업. 베트남 진출을 고민하는 창업가에게 현실적인 시장의 온도를 전합니다.',
    specialties: ['startup-networking'],
    languages: ['ko', 'en', 'vi'],
    yearsOfExperience: 8,
    baseCitySlug: 'ho-chi-minh',
    serviceAreaSlugs: ['ho-chi-minh', 'hanoi'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'saigon-bootcamp',
        categorySlug: 'startup-networking',
        title: '호찌민 창업 부트캠프 4주',
        short: '시장조사·현지 파트너·투자자 미팅까지 이어지는 실전 과정.',
        full: '베트남 시장 진출을 검증하는 4주 부트캠프입니다. 산업 리서치, 현지 창업가 밋업, 마지막 주 투자자·파트너 미팅 주선까지 진행합니다.',
        programType: 'GROUP',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 8,
        tier: 'high',
        featured: true,
        includes: ['워크숍 4회', '밋업 3회', '미팅 주선 최대 3건'],
      },
      {
        slugSuffix: 'market-mentoring',
        categorySlug: 'startup-networking',
        title: '1:1 베트남 시장조사 멘토링',
        short: '아이템 검증을 위한 주 1회 심층 멘토링.',
        full: '창업 아이템의 베트남 적합성을 검증하는 1:1 멘토링입니다. 유통 구조, 규제, 가격대 조사를 함께 설계하고 리뷰합니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 1,
        tier: 'mid',
        includes: ['심층 멘토링 4회', '리서치 템플릿', '현지 연락처 소개'],
      },
    ],
  },
  {
    slug: 'pham-huong',
    email: 'pham.huong@seed.invalid',
    name: 'Pham Huong',
    fullName: 'Pham Thi Huong',
    displayName: '흐엉의 하노이 부엌',
    bio: '3대째 이어온 하노이 가정식. 퍼 국물의 비밀부터 골목 미식 지도까지 알려드립니다.',
    specialties: ['cooking-food', 'travel-culture'],
    languages: ['vi', 'en'],
    yearsOfExperience: 14,
    baseCitySlug: 'hanoi',
    serviceAreaSlugs: ['hanoi'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'hanoi-home-cooking',
        categorySlug: 'cooking-food',
        title: '하노이 가정식 클래스 4주',
        short: '퍼·분짜·반쎄오 — 주 2회 시장 장보기와 요리.',
        full: '구시가지 시장에서 장을 보고 가정집 부엌에서 요리하는 하노이 가정식 클래스입니다. 8회 동안 대표 요리 12가지를 다룹니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 6,
        tier: 'low',
        includes: ['클래스 8회', '재료비', '레시피 노트'],
        meetingPoint: '동쑤언 시장 정문',
      },
      {
        slugSuffix: 'hanoi-food-tour',
        categorySlug: 'cooking-food',
        title: '하노이 골목 미식 탐험',
        short: '주 1회, 현지인만 아는 노포 미식 투어 4회.',
        full: '관광 지도에 없는 골목 노포를 찾아가는 미식 투어입니다. 매주 다른 테마(쌀국수·분류·카페·야시장)로 진행합니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 6,
        tier: 'mid',
        includes: ['미식 투어 4회', '시식 비용', '미식 지도'],
      },
    ],
  },
  {
    slug: 'jang-hyunwoo',
    email: 'jang.hyunwoo@seed.invalid',
    name: '장현우',
    fullName: '장현우',
    displayName: '현우 포토',
    bio: '내셔널지오그래픽 공모전 수상 사진가. 하노이의 빛과 골목을 담는 법을 가르칩니다.',
    specialties: ['photo-video'],
    languages: ['ko', 'en'],
    yearsOfExperience: 9,
    baseCitySlug: 'hanoi',
    serviceAreaSlugs: ['hanoi', 'da-nang'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'photo-coaching',
        categorySlug: 'photo-video',
        title: '한 달의 기록 — 1:1 사진 코칭',
        short: '촬영 동행과 리뷰로 완성하는 나만의 포토 에세이.',
        full: '주 1회 촬영 동행과 주 1회 사진 리뷰로 구성된 1:1 코칭입니다. 마지막 주에는 한 달의 기록을 20장의 포토 에세이로 엮습니다.',
        programType: 'PRIVATE',
        bookingType: 'REQUEST',
        durationDays: 28,
        sessionCount: 8,
        maxParticipants: 1,
        tier: 'mid',
        includes: ['촬영 동행 4회', '리뷰 세션 4회', '포토 에세이 편집'],
        requirements: ['카메라 또는 스마트폰'],
      },
      {
        slugSuffix: 'photo-walk',
        categorySlug: 'photo-video',
        title: '하노이 새벽 포토워크',
        short: '주 1회 새벽, 구시가지·기찻길·호안끼엠을 걷는 촬영 모임.',
        full: '빛이 가장 좋은 새벽 시간, 하노이의 장면들을 함께 걸으며 담는 소그룹 포토워크입니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 6,
        tier: 'low',
        includes: ['포토워크 4회', '베스트컷 피드백'],
        meetingPoint: '호안끼엠 호수 북단',
      },
    ],
  },
  {
    slug: 'le-thao',
    email: 'le.thao@seed.invalid',
    name: 'Le Thao',
    fullName: 'Le Thi Thao',
    displayName: '타오의 나트랑',
    bio: '나트랑 토박이 가이드. 호핑투어 보트 위에서도, 새벽 어시장에서도 나트랑의 진짜 얼굴을 보여드립니다.',
    specialties: ['travel-culture', 'surfing'],
    languages: ['vi', 'ko', 'en'],
    yearsOfExperience: 6,
    baseCitySlug: 'nha-trang',
    serviceAreaSlugs: ['nha-trang'],
    verificationStatus: 'APPROVED',
    programs: [
      {
        slugSuffix: 'local-life',
        categorySlug: 'travel-culture',
        title: '나트랑 로컬 라이프 4주',
        short: '어시장·짬탑·머드온천 — 주 1회 로컬 동행.',
        full: '새벽 어시장 장보기, 포나가르 짬탑, 현지인 머드온천까지 관광 바깥의 나트랑을 매주 하나씩 경험합니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 8,
        tier: 'low',
        childFriendly: true,
        includes: ['동행 투어 4회', '입장료', '로컬 지도'],
      },
      {
        slugSuffix: 'island-marine',
        categorySlug: 'surfing',
        title: '나트랑 아일랜드 마린 클럽',
        short: '주 1회 호핑·스노클링·카약 해양 액티비티 클럽.',
        full: '나트랑 앞바다 섬들을 도는 주 1회 해양 액티비티 프로그램입니다. 스노클링 포인트와 카약, 선상 점심이 포함됩니다.',
        programType: 'GROUP',
        bookingType: 'INSTANT',
        durationDays: 28,
        sessionCount: 4,
        maxParticipants: 10,
        tier: 'mid',
        transportIncluded: true,
        includes: ['보트 투어 4회', '스노클링 장비', '선상 점심'],
        requirements: ['기초 수영 권장'],
      },
    ],
  },
];
